//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookidea {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cookidea.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string btn_search {
            get {
                return ResourceManager.GetString("btn_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered a wrong input text. Please, use only words and commas and search again..
        /// </summary>
        public static string da_input_desc {
            get {
                return ResourceManager.GetString("da_input_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Input.
        /// </summary>
        public static string da_input_title {
            get {
                return ResourceManager.GetString("da_input_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no internet connection. Please check your connection and try again..
        /// </summary>
        public static string da_internet_desc {
            get {
                return ResourceManager.GetString("da_internet_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Connection.
        /// </summary>
        public static string da_internet_title {
            get {
                return ResourceManager.GetString("da_internet_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string da_ok {
            get {
                return ResourceManager.GetString("da_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chocolate, caramel....
        /// </summary>
        public static string et_ingredients {
            get {
                return ResourceManager.GetString("et_ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search recipes by ingredients!.
        /// </summary>
        public static string lbl_1 {
            get {
                return ResourceManager.GetString("lbl_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (separate ingredients with a comma).
        /// </summary>
        public static string lbl_2 {
            get {
                return ResourceManager.GetString("lbl_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookidea.
        /// </summary>
        public static string title_main {
            get {
                return ResourceManager.GetString("title_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        public static string title_result {
            get {
                return ResourceManager.GetString("title_result", resourceCulture);
            }
        }
    }
}
