//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookidea {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Cookidea.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        public static string AlertInputDesc {
            get {
                return ResourceManager.GetString("AlertInputDesc", resourceCulture);
            }
        }
        
        public static string AlertInputTitle {
            get {
                return ResourceManager.GetString("AlertInputTitle", resourceCulture);
            }
        }
        
        public static string AlertInternetDesc {
            get {
                return ResourceManager.GetString("AlertInternetDesc", resourceCulture);
            }
        }
        
        public static string AlertInternetTitle {
            get {
                return ResourceManager.GetString("AlertInternetTitle", resourceCulture);
            }
        }
        
        public static string AlertNoResultsDesc {
            get {
                return ResourceManager.GetString("AlertNoResultsDesc", resourceCulture);
            }
        }
        
        public static string AlertNoResultsTitle {
            get {
                return ResourceManager.GetString("AlertNoResultsTitle", resourceCulture);
            }
        }
        
        public static string AlertOk {
            get {
                return ResourceManager.GetString("AlertOk", resourceCulture);
            }
        }
        
        public static string EntryIngredients {
            get {
                return ResourceManager.GetString("EntryIngredients", resourceCulture);
            }
        }
        
        public static string Lbl1 {
            get {
                return ResourceManager.GetString("Lbl1", resourceCulture);
            }
        }
        
        public static string Lbl2 {
            get {
                return ResourceManager.GetString("Lbl2", resourceCulture);
            }
        }
        
        public static string TitleMain {
            get {
                return ResourceManager.GetString("TitleMain", resourceCulture);
            }
        }
        
        public static string TitleResult {
            get {
                return ResourceManager.GetString("TitleResult", resourceCulture);
            }
        }
        
        public static string TitleFav {
            get {
                return ResourceManager.GetString("TitleFav", resourceCulture);
            }
        }
        
        public static string AlertFavAddedDesc {
            get {
                return ResourceManager.GetString("AlertFavAddedDesc", resourceCulture);
            }
        }
        
        public static string AlertFavDeletedDesc {
            get {
                return ResourceManager.GetString("AlertFavDeletedDesc", resourceCulture);
            }
        }
        
        public static string AlertNoFavsDesc {
            get {
                return ResourceManager.GetString("AlertNoFavsDesc", resourceCulture);
            }
        }
        
        public static string NoFavRecipes {
            get {
                return ResourceManager.GetString("NoFavRecipes", resourceCulture);
            }
        }
    }
}
