//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookidea {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cookidea.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe added to favorites.
        /// </summary>
        public static string AlertFavAddedDesc {
            get {
                return ResourceManager.GetString("AlertFavAddedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe deleted from favorites.
        /// </summary>
        public static string AlertFavDeletedDesc {
            get {
                return ResourceManager.GetString("AlertFavDeletedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered a wrong input text. Please, use only words and commas and search again..
        /// </summary>
        public static string AlertInputDesc {
            get {
                return ResourceManager.GetString("AlertInputDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Input.
        /// </summary>
        public static string AlertInputTitle {
            get {
                return ResourceManager.GetString("AlertInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no internet connection. Please check your connection and try again..
        /// </summary>
        public static string AlertInternetDesc {
            get {
                return ResourceManager.GetString("AlertInternetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Connection.
        /// </summary>
        public static string AlertInternetTitle {
            get {
                return ResourceManager.GetString("AlertInternetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites list is empty.
        /// </summary>
        public static string AlertNoFavsDesc {
            get {
                return ResourceManager.GetString("AlertNoFavsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! We didn&apos;t found a recipe that matches your ingredients! Try again with other ingredients! :).
        /// </summary>
        public static string AlertNoResultsDesc {
            get {
                return ResourceManager.GetString("AlertNoResultsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        public static string AlertNoResultsTitle {
            get {
                return ResourceManager.GetString("AlertNoResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string AlertOk {
            get {
                return ResourceManager.GetString("AlertOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chocolate, caramel....
        /// </summary>
        public static string EntryIngredients {
            get {
                return ResourceManager.GetString("EntryIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search recipes by ingredients!.
        /// </summary>
        public static string Lbl1 {
            get {
                return ResourceManager.GetString("Lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (separate ingredients with a comma).
        /// </summary>
        public static string Lbl2 {
            get {
                return ResourceManager.GetString("Lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string TitleFav {
            get {
                return ResourceManager.GetString("TitleFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookidea.
        /// </summary>
        public static string TitleMain {
            get {
                return ResourceManager.GetString("TitleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        public static string TitleResult {
            get {
                return ResourceManager.GetString("TitleResult", resourceCulture);
            }
        }
    }
}
